### ISSUE TITLE
Create workshop syllabus for Cardano Indonesia

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-workshops#1]
**Tasks:**

- [x] Create workshop syllabus for Cardano Indonesia
- [x] Publish in Cardano Forum
- [x] Publish as README.md in GitHub repository

**Comment by andreassosilo** [comment]
Adding the syllabus in Cardano Forum and also GitHub. Create README.md for the workshop repository.
