### ISSUE TITLE
Cardano Indonesia Workshops - 03: Cardano Ecosystem - 23 January 2022

### ISSUE THREAD

**Issue by andrecahyadi** [cardano-indonesia/cardano-indonesia-workshops#14]
- Last Workshop - #12 
- Next Workshop - #5 

### Team
Host: @andreassosilo 
Co-host: @andrecahyadi 
Speakers: @dionsetyotomo & @jordyvincent 

### Tasks

- [ ] Create Meetup event @andreassosilo 
- [ ] Schedule Zoom meeting using Cardano Indonesia account @andreassosilo 
- [ ] Inform the event in Forum Cardano Indonesia @andreassosilo 
- [ ] Inform the event in Discord Cardano Indonesia @andreassosilo
- [ ] Inform the event in Telegram Group @andreassosilo 
- [ ] Inform the event in Instagram @jordyvincent
- [ ] Inform the event in Twitter @jordyvincent 
- [ ] Team meeting on Friday, 18 February 2022
- [ ] Record Zoom meeting @andreassosilo 
- [ ] Take a note on who wins the door prize & rewards @andrecahyadi  
- [ ] Send door prize & rewards @andrecahyadi 
- [ ] Payment for compensation by coordinator @andreassosilo 
- [ ] Update Google Sheet for project spending @andrecahyadi 
- [ ] Video editing @zicozibu 
- [ ] Uploading video to Cardano Indonesia YouTube Channel @zicozibu 
- [ ] Create summary of the event in Cardano Forum @andreassosilo 
- [ ] Reporting KPI & project progress to IOG & Catalyst Team @andreassosilo
