### ISSUE TITLE
Cardano Indonesia Workshops - 07: Introduction to Self-Sovereign Identity & Atala PRISM - 03 April 2022

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-workshops#16]
## Cardano Indonesia Workshops - 07: Introduction to Self-Sovereign Identity & Atala PRISM - 03 April 2022
- Last Workshop - #10 
- Next Workshop - TBD 

### Team
- Host: @dionsetyotomo 
- Co-host: @andrecahyadi 
- Speaker: @andreassosilo 

### Tasks

- [x] Create Meetup event @andreassosilo 
- [x] Schedule Zoom meeting using Cardano Indonesia account @andreassosilo 
- [x] Inform the event in Forum Cardano Indonesia @andreassosilo 
- [x] Inform the event in Discord Cardano Indonesia & EMURGO Indonesia @dionsetyotomo 
- [x] Inform the event in Telegram Group @dionsetyotomo 
- [ ] Inform the event in Instagram @jordyvincent
- [ ] Inform the event in Twitter @jordyvincent 
- [ ] Flyer Design @YanTirta
- [ ] Team meeting on Friday, 01 April 2022
- [ ] Record Zoom meeting @dionsetyotomo 
- [ ] Take a note on who wins the door prize & rewards @andrecahyadi  
- [ ] Send door prize & rewards @andrecahyadi 
- [ ] Payment for compensation by coordinator @andreassosilo 
- [ ] Update Google Sheet for project spending @andrecahyadi 
- [ ] Video editing @dionsetyotomo 
- [ ] Uploading video to Cardano Indonesia YouTube Channel @dionsetyotomo 
- [ ] Create summary of the event in Cardano Forum @andreassosilo 
- [ ] Reporting KPI & project progress to IOG & Catalyst Team @andreassosilo 

### Summary

- Summary for Introduction to Self-Sovereign Identity & Atala PRISM Workshop
