### ISSUE TITLE
Cardano Indonesia Workshops - 01: How to Become CA in Project Catalyst - 17 October 2021

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-workshops#18]
## Cardano Indonesia Workshops - 01: How to Become CA in Project Catalyst - 17 October 2021
- Next Workshop - #19 

### Team
- Host: @andreassosilo 
- Speakers: @andreassosilo & @YanTirta 

### Tasks

- [x] Create [Meetup event](https://www.meetup.com/Cardano-Blockchain-Jakarta/events/283424479/) @andreassosilo 
- [x] Schedule Zoom meeting using Cardano Indonesia account @andreassosilo 
- [x] Inform the event in Forum Cardano Indonesia @andreassosilo 
- [x] Inform the event in Discord Cardano Indonesia @andreassosilo
- [x] Inform the event in Telegram Group @andreassosilo 
- [x] Inform the event in Instagram @jordyvincent
- [x] Inform the event in Twitter @jordyvincent 
- [x] Record Zoom meeting @andreassosilo 
- [x] Upload workshop video recording to Google Drive @andreassosilo
- [ ] Payment for compensation by coordinator @andreassosilo 
- [x] Update Google Sheet for project spending @andreassosilo
- [ ] Video editing @dionsetyotomo 
- [ ] Upload edited video to [Cardano Indonesia YouTube Channel](https://www.youtube.com/channel/UCskq7Po4Hkyvlv7dAcFuY8g) @dionsetyotomo 
- [x] Create summary of the event in Cardano Forum @andreassosilo 
- [x] Reporting KPI & project progress to IOG & Catalyst Team @andreassosilo 

### Summary

- [Meetup Event: "How to Become CA in Project Catalyst"](https://www.meetup.com/Cardano-Blockchain-Jakarta/events/281363257/)
- [Summary in Cardano Forum for "How to Become CA in Project Catalyst" Workshop](https://forum.cardano.org/t/cardano-hub-jakarta-workshop-cara-menjadi-community-advisor-di-project-catalyst/79257/2)
- [YouTube Video Documentation](https://www.youtube.com/channel/UCskq7Po4Hkyvlv7dAcFuY8g)
