### ISSUE TITLE
Cardano Indonesia Workshops: Cardano Ecosystem - 23 January 2022

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-workshops#2]
**Tasks:**

- [x] Create Meetup event for Cardano Ecosystem in Meetup Cardano Hub Jakarta
- [x] Inform the event in Cardano Forum
- [x] Inform the event in Telegram Cardano Indonesia, Eastern Town Hall Indonesia and EMURGO Indonesia
- [x] Inform the event in Discord Cardano Indonesia
- [x] Preparation of the topic with @dionsetyotomo & @jordyvincent via Whatsapp Group
- [x] Host the event via Zoom
- [x] Create summary in Cardano Forum

**Comment by andreassosilo** [comment]
Event is hosted on Sunday, 23 Jan 2022. 

Meetup can be checked in https://www.meetup.com/Cardano-Blockchain-Jakarta/events/283036339/

Summary is created in Cardano Forum, see: https://forum.cardano.org/t/cardano-hub-jakarta-meetup-diskusi-mengenai-ekosistem-cardano-23-jan-2022/90763

**Comment by andrecahyadi** [comment]
Gw revive lagi ini issue supaya saling menyambung dengan issue workshop lainnya
