### ISSUE TITLE
Participate in Catalyst Coordinator Meeting - 22 March 2022

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-workshops#20]
**Tasks:**

- [x] Attend the coordinator meeting
- [x] Get the [presentation link](https://docs.google.com/presentation/d/131eYNysBM-cYkq1HgoewpJ6mKz-2G2KQ6JclbNpAV-U/edit#slide=id.g10207710c5f_0_0)
- [x] Get [Catalyst Coordinator GitBook](https://catalyst-circle.gitbook.io/catalyst-coordinator/information/meetings)
- [x] Get [Challenge Team GitBook](https://quality-assurance-dao.gitbook.io/improve-and-grow-auditability/challenge-team/challenge-team-process)
- [x] Give presentation about project progress in from February to March 2022

**Comment by andreassosilo** [comment]
Done. Give the presentation in breakout room 1 with TK Prince. Session is recorded.
