### ISSUE TITLE
Participate in Catalyst Coordinator Meeting - 05 April 2022

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-workshops#21]
**Tasks:**

- [x] Participate in Catalyst Coordinator Meeting on Tuesday, 05 April 2022
- [x] Get meeting [slides](https://docs.google.com/presentation/d/131eYNysBM-cYkq1HgoewpJ6mKz-2G2KQ6JclbNpAV-U/edit#slide=id.gb756fa1b15_0_0)
- [x] Presented the progress of the project
- [x] Link for [Public Catalyst Monthly Reporting](https://docs.google.com/spreadsheets/d/1wAG5O4PBLRTM01PLUyc3iS9EYOaucyDHryOOG8OVKuk/edit#gid=0)

**Comment by andreassosilo** [comment]
Done. Closed.
