### ISSUE TITLE
Cardano Indonesia Workshops - 11: Introduction to Cardano Wallet & AMA - 15 May 2022

### ISSUE THREAD

**Issue by andrecahyadi** [cardano-indonesia/cardano-indonesia-workshops#22]
## Cardano Indonesia Workshops - 11: Cardano Ecosystem - 15 May 2022
- Last Workshop - #17
- Next Workshop - #23

### Team
- Host: @andreassosilo 
- Co-host: @andrecahyadi 
- Speakers: @zicozibu & @dionsetyotomo

### Tasks

- [x] Create Meetup event @andreassosilo 
- [x] Schedule Zoom meeting using Cardano Indonesia account @andreassosilo 
- [ ] Inform the event in Forum Cardano Indonesia @andreassosilo 
- [ ] Inform the event in Discord Cardano Indonesia & EMURGO Indonesia @andreassosilo
- [ ] Inform the event in Telegram Group @andreassosilo 
- [ ] Inform the event in Instagram @jordyvincent
- [ ] Inform the event in Twitter @CryptoCaliburn 
- [ ] Flyer Design @YanTirta
- [ ] Team meeting on Friday, 13 May 2022
- [ ] Record Zoom meeting @andreassosilo 
- [x] Create a mini game for door prize & rewards @andrecahyadi  
- [x] Send door prize & rewards @andrecahyadi 
- [ ] Payment for compensation by coordinator @andreassosilo 
- [x] Update Google Sheet for project spending @andrecahyadi 
- [ ] Video editing @dionsetyotomo 
- [ ] Uploading video to Cardano Indonesia YouTube Channel @dionsetyotomo 
- [ ] Create summary of the event in Cardano Forum @andreassosilo 
- [ ] Reporting KPI & project progress to IOG & Catalyst Team @andreassosilo
