### ISSUE TITLE
Cardano Indonesia Workshops - 12: Cardano Ecosystem - 29 May 2022

### ISSUE THREAD

**Issue by andrecahyadi** [cardano-indonesia/cardano-indonesia-workshops#23]
## Cardano Indonesia Workshops - 12: Cardano Ecosystem - 29 May 2022
- Last Workshop - #22
- Next Workshop - #24

### Team
- Host: @andreassosilo 
- Co-host: @andrecahyadi 
- Speakers: @CryptoCaliburn, @dionsetyotomo, & Darma from KITA Cardano

### Tasks

- [ ] Create Meetup event @andreassosilo 
- [ ] Schedule Zoom meeting using Cardano Indonesia account @andreassosilo 
- [ ] Inform the event in Forum Cardano Indonesia @andreassosilo 
- [ ] Inform the event in Discord Cardano Indonesia & EMURGO Indonesia @andreassosilo
- [ ] Inform the event in Telegram Group @andreassosilo 
- [ ] Inform the event in Instagram @jordyvincent
- [ ] Inform the event in Twitter @CryptoCaliburn 
- [ ] Flyer Design @YanTirta
- [ ] Team meeting on Friday, 27 May 2022
- [ ] Record Zoom meeting @andreassosilo 
- [x] Send door prize & rewards @andrecahyadi 
- [ ] Payment for compensation by coordinator @andreassosilo 
- [x] Update Google Sheet for project spending @andrecahyadi 
- [ ] Video editing @dionsetyotomo 
- [ ] Uploading video to Cardano Indonesia YouTube Channel @dionsetyotomo 
- [ ] Create summary of the event in Cardano Forum @andreassosilo 
- [ ] Reporting KPI & project progress to IOG & Catalyst Team @andreassosilo
