### ISSUE TITLE
Cardano Indonesia Workshops: Cardano Ecosystem - 23 January 2022

### ISSUE THREAD

**Issue by andrecahyadi** [cardano-indonesia/cardano-indonesia-workshops#27]
**Tasks:**

- [x] #29
- [x] Inform the event in Cardano Forum
- [x] Inform the event in Telegram Cardano Indonesia, Eastern Town Hall Indonesia and EMURGO Indonesia
- [x] Inform the event in Discord Cardano Indonesia
- [x] Preparation of the topic with @dionsetyotomo & @jordyvincent via Whatsapp Group
- [x] Host the event via Zoom
- [x] Create summary in Cardano Forum
