### ISSUE TITLE
Cardano Indonesia Workshops - 15: Cross Chain Ecosystem AMA with Vexanium - 10 July 2022

### ISSUE THREAD

**Issue by andrecahyadi** [cardano-indonesia/cardano-indonesia-workshops#30]
## Cardano Indonesia Workshops - 15: Cross Chain Ecosystem AMA with Vexanium - 10 July 2022
- Last Workshop - #25  
- Next Workshop - #31 

### Team
- Host: @andreassosilo 
- Co-host: @andrecahyadi   
- Speakers: @andreassosilo, Arif Atoillah (Business Development Vexanium)

### Tasks

- [ ] Create Meetup event @andreassosilo 
- [ ] Schedule Zoom meeting using Cardano Indonesia account @andreassosilo 
- [ ] Inform the event in Forum Cardano Indonesia @andreassosilo 
- [ ] Inform the event in Discord Cardano Indonesia & EMURGO Indonesia @andreassosilo
- [ ] Inform the event in Telegram Group @andreassosilo 
- [ ] Inform the event in Instagram @jordyvincent
- [ ] Inform the event in Twitter @CryptoCaliburn 
- [ ] Flyer Design @YanTirta
- [ ] Team meeting on Friday, 24 Jun 2022
- [ ] Record Zoom meeting @andreassosilo 
- [x] Send door prize & rewards @andrecahyadi 
- [ ] Payment for compensation by coordinator @andreassosilo 
- [x] Update Google Sheet for project spending @andrecahyadi 
- [ ] Video editing @dionsetyotomo 
- [ ] Uploading video to Cardano Indonesia YouTube Channel @dionsetyotomo 
- [ ] Create summary of the event in Cardano Forum @andreassosilo 
- [ ] Reporting KPI & project progress to IOG & Catalyst Team @andreassosilo
