### ISSUE TITLE
Send rewards for Cardano Indonesia Workshop - Cardano Ecosystem (23 Jan 2022)

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-workshops#4]
**Tasks:**

- [x] Send 10 MILK token + 1.5 ADA for door prize winner to Bagas Samuel
- [x] Send 10 MILK token + 1.5 ADA for door prize winner to Tegar
- [x] Send 10 MILK token + 1.5 ADA for Twitter Giveaway Winner to https://twitter.com/Abhi6969 
- [x] Send 10 ADA for the best question to Divan F

**Comment by andreassosilo** [comment]
Done. Rewards sent.
