### ISSUE TITLE
Participate in Catalyst Coordinator Meeting - 01 November 2022

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-workshops#40]
**Tasks:**

- [x] Participate in Catalyst Coordinator Meeting on Tuesday, 01 November 2022
- [x] Get meeting [slides](https://docs.google.com/presentation/d/1tKJvMTcZ-5s2AzqtLTHSSTbgF7QS1N6BSnVqp9kfvm0/edit#slide=id.g14050be1a2c_0_1325)
- [x] Presented the progress of the project
- [x] Link for [Public Catalyst Monthly Reporting](https://bit.ly/CatalystMonthlyReport)
