### ISSUE TITLE
Cardano Indonesia Workshops: Cardano Ecosystem - 20 February 2022

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-workshops#5]
**Tasks:**

- [x] Create Meetup event for Cardano Ecosystem in Meetup Cardano Hub Jakarta
- [x] Inform the event in Cardano Forum
- [x] Inform the event in Telegram Cardano Indonesia, Eastern Town Hall Indonesia and EMURGO Indonesia
- [x] Inform the event in Discord Cardano Indonesia
- [ ] Inform the event in Instagram Cardano Indonesia
- [x] Preparation of the topic with @andrecahyadi , @dionsetyotomo & @jordyvincent
- [x] Host the event via Zoom Cardano Indonesia
- [x] Create summary in Cardano Forum
- [ ] Record the workshop
- [ ] Editing the workshop video
- [ ] Upload the edited video to Cardan Indonesia YouTube Channel
- [ ] Collect the doorprize and giveaway winner
- [ ] Send the rewards the the winner

**Comment by andrecahyadi** [comment]
@andreassosilo Workshop yang tgl 23 Jan 2022 mau di-input juga kah?

**Comment by andrecahyadi** [comment]
Draft bullet points yang lo buat @andreassosilo (gw gak hapus, gw taro di comments aja)
- [ ] Create Meetup event for Cardano Ecosystem in Meetup Cardano Hub Jakarta
- [ ] Inform the event in Cardano Forum
- [ ] Inform the event in Telegram Cardano Indonesia, Eastern Town Hall Indonesia and EMURGO Indonesia
- [ ] Inform the event in Discord Cardano Indonesia
- [ ] Inform the event in Instagram Cardano Indonesia
- [ ] Preparation of the topic with @andrecahyadi , @dionsetyotomo & @jordyvincent
- [ ] Host the event via Zoom Cardano Indonesia
- [ ] Create summary in Cardano Forum
- [ ] Record the workshop
- [ ] Editing the workshop video
- [ ] Upload the edited video to Cardan Indonesia YouTube Channel
- [ ] Collect the doorprize and giveaway winner
- [ ] Send the rewards the the winner

**Comment by andreassosilo** [comment]
> @andreassosilo Gw revive issue untuk workshop tgl 23 Jan 2022 juga ya

okay bro @andrecahyadi , revive dulu aja. Kita tambahin bullet point atau tasks. Entar gw rapiin. Sorry, kemarin gw belom sempat rapiin. Lagi ngerjain recap. Thank you bantuannya.
