### ISSUE TITLE
Fund 7 Onboarding - Session A

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-workshops#6]
**Tasks:**

- [x] Attend Catalyst Fund 7 onboarding session A (Duration: 2 hours)
- [x] Introduce our project
- [x] Get the important information
- [x] Get the project ID
- [x] Fill the feedback form for Fund 7 Onboarding Session

**Comment by andreassosilo** [comment]
Check this documentation for our project ID (700041):
https://docs.google.com/spreadsheets/d/1bfnWFa94Y7Zj0G7dtpo9W1nAYGovJbswipxiHT4UE3g/edit#gid=793243167

**Comment by andreassosilo** [comment]
Catalyst Fund 7 Cohort Onboarding presentation: https://docs.google.com/presentation/d/19jkrAIks6f4Y4DZvnKEly2HDT9dJIjzwa1ofEYkR10o/edit#slide=id.g11522e9b3aa_0_0

**Comment by andreassosilo** [comment]
Done, attended the onboarding and will prepare the necessary tasks/issues in workshops repositories.
