### ISSUE TITLE
Prepare requested batch of fund for March 2022

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-workshops#7]
**Tasks:**

- [x] Create budget breakdown for already running workshops
- [x] E-mail to catalyst@iohk.io
- [x] Contact Marek Buchowiecki and Daniel Ribar
- [x] Inform why we need accelerated funding and the reasoning

**Comment by andreassosilo** [comment]
Done. Email sent to catalyst@iohk.io with reasoning + budget break down details.
